chrome trace
asChromeTraceExample
	
	^  {
			#traceEvents -> {
			({
					#pid -> 1.
					#tid -> 1.
					#ts -> 87705.
					#dur -> 956189.
					#ph -> 'X'.
					#name -> 'Jambase'.
					#args -> ({#ms -> 956.2}  as: Dictionary).
			 } as: Dictionary).
			({
					#pid -> 1.
					#tid -> 1.
					#ts -> 128154.
					#dur -> 75867.
					#ph -> 'X'.
					#name -> 'SyncTargets'.
					#args -> ({#ms -> 75.9}  as: Dictionary).
			 } as: Dictionary).
			({
					#pid -> 1.
					#tid -> 1.
					#ts -> 546867.
					#dur -> 121564.
					#ph -> 'X'.
					#name -> 'DoThings'.
					#args -> ({#ms -> 121.6}  as: Dictionary).
			 } as: Dictionary)
		}} as: Dictionary
